- name: Format the filesystem
  filesystem:
    fstype: "{{ fstype }}"
    dev: "{{ device }}"
  when: device is defined

- name: Check if the directory to be created already exists
  stat:
    path: "{{ mountpoint }}"
  register: dir_stat
  
- name: Create Directory 
  file:
    path: "{{ mountpoint }}"
    recurse: yes
    state: directory
    mode: 0755
    owner: ec2-user
    group: ec2-user
  when: dir_stat.stat.exists == false

- name: Mount device 
  mount:
    path: "{{ mountpoint }}"
    src: "{{ item }}"
    fstype: "{{ fstype }}"
    state: mounted
  when: item  is defined
  with_items:
    - "{{ device }}"

- name: Changing ownership of mounted folder to ec2-user
  file:
    path: "{{ mountpoint }}"
    owner: ec2-user
    group: ec2-user
    mode: 0755
