---
# Create CouchDB cluster

- name: Enable the cluster
  shell: curl -X POST -H "Content-Type:application/json" http://{{ couch_admin_user }}:{{ couch_admin_password }}@{{ groups.dbserver[0] }}:5984/_cluster_setup -d '{"action":"enable_cluster", "bind_address":"{{ bind_address }}", "username":"{{ couch_admin_user }}", "password":"{{ couch_admin_password }}", "port":5984, "node_count":3 , "remote_node":"{{ item }}", "remote_current_user":"{{ couch_admin_user }}", "remote_current_password":"{{ couch_admin_password }}" }'
  with_items: "{{groups['dbserver']}}"
 
- name: Add nodes to the cluster
  shell: curl -X POST -H "Content-Type:application/json" http://{{ couch_admin_user }}:{{ couch_admin_password }}@{{ groups.dbserver[0] }}:5984/_cluster_setup -d '{"action":"add_node", "host":"{{ item }}", "port":5984, "username":"{{ couch_admin_user }}", "password":"{{ couch_admin_password }}"}'
  with_items: "{{groups['dbserver']}}"
  when: inventory_hostname == "{{ groups.dbserver[0] }}"

- name: Finish the cluster
  shell: curl -X POST -H "Content-Type:application/json" http://{{ couch_admin_user }}:{{ couch_admin_password }}@{{ groups.dbserver[0] }}:5984/_cluster_setup -d '{"action":"finish_cluster"}'
  when: inventory_hostname == "{{ groups.dbserver[0] }}"
